[package]
name = "log_experiments"
version = "0.1.0"
authors = ["Denis Otkidach <denis.otkidach@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
git-version = "0.3"
hostname = "0.3"
lazy_static = "1"
log = "0.4"
regex = "1"
slog = "2"
slog-async = "2"
slog-gelf = "0.1.2"
slog-scope = "4"
slog-term = "2"
